docs: system dependencies are not always available
apache/maven-site pull request #191
Opened 2020-08-04 19:45 UTC by elharo

@michael-o

2020-08-04 20:08 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
If it is not added to a classpath, what's the point in having them?

2020-08-04 20:31 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
They're usually (though not always) in the classpath but Maven doesn't put them there. The JVM (or something else) does.

2020-08-04 20:34 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
But at least for compilation purposes it is in the classpath or maybe at runtime available.

2020-08-04 21:14 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
The keyword is "maybe". There's no guarantee it is, and the current text makes it sound like this is guaranteed. The case that made me pay attention to this was Guava doing a complicated dance to load src.zip for use in javaDoc:

```
   <profile>
      <id>srczip-parent</id>
      <activation>
        <file>
          <exists>${java.home}/../src.zip</exists>
        </file>
      </activation>
      <dependencies>
        <dependency>
          <groupId>jdk</groupId>
          <artifactId>srczip</artifactId>
          <version>999</version>
          <scope>system</scope>
          <systemPath>${java.home}/../src.zip</systemPath>
          <optional>true</optional>
        </dependency>
      </dependencies>
    </profile>
```

2020-08-04 21:17 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
I don't see the maybe in the modified text.

2020-08-11 17:30 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
I was referring to the "maybe"in your comment. :-)

2020-12-28 19:53 UTC, michael-o requested changes

2020-12-28 19:53 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
I fo not agree with this. @rfscholte

2023-04-15 10:43 UTC, elharo commented
Ping @rfscholte 

I still think this doc change is needed. The current documentation is simply incorrect.

2023-04-18 14:40 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
It is unfortunately that easy and it is not just the JDK

* https://issues.apache.org/jira/browse/MNG-1867
* https://issues.apache.org/jira/browse/MNG-6523
* The idiot's from SAP have hardoded the JCo JAR name and it won't start if you rename it
* JAR which people aren't allowed for reasons to upload to a local repo instance
* likely others

2023-04-19 11:06 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> +   Maven does not add system-scoped dependencies to any classpath.
It's been a while but this came up a couple of project ago in my day job, where we spent a lot of effort untangling different kinds of dependency scopes and analyzing dependency graphs. The existing text is wrong in one key respect:

"Dependencies with the scope system are always available and are not looked up in repository." 

However, dependencies with the scope system are *not* "always available". Declaring a dependency such as 

```
<dependency>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>4.0.0-M7</version>
          <scope>system</scope>
</dependency>
```

doesn't magically make it available. This is likely just sloppy writing, and the intent was to document the correct behavior but that's not how the text reads  currently, especially to a dev not steeped in Maven dependency management. 

Let me take another stab at rephrasing this to take into account the points you bring up about non-classpath based resolution of dependencies.

2023-04-19 11:40 UTC, elharo reviewed
PTAL

2023-04-20 17:37 UTC, rfscholte commented
LGTM

2023-04-20 19:12 UTC, michael-o requested changes

2023-04-20 19:12 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
I don't even know whether the cae with JDBC and JAAS is still true. I'd try to avoid giving example which are invalid in a couple of years.

2023-04-20 19:38 UTC, elharo commented on pom.xml
> -    <project.build.outputTimestamp>x</project.build.outputTimestamp><!-- disable Reproducible Builds that makes the site build time fixed at last release time -->
Yes, but necessary or the build breaks. I am less find of how spotless has been integrated every day. :-(

2023-04-20 19:43 UTC, michael-o commented on pom.xml
> -    <project.build.outputTimestamp>x</project.build.outputTimestamp><!-- disable Reproducible Builds that makes the site build time fixed at last release time -->
Spotless 1🤣

2023-04-20 22:02 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
I think it is. Per Oracle docs, "The Java Authentication and Authorization Service (JAAS) was introduced as an optional package (extension) to the Java 2 SDK, Standard Edition (J2SDK), v 1.3. JAAS was integrated into the J2SDK 1.4." Unless Oracle decides to remove it again, this statement seems likely to be true for the indefinite future. 

Though now that I think about it, I don't really see how this helps to to tell Maven about dependencies provided by the JDK or the VM. If you're in a VM that includes them, this is unnecessary and if you're not then a system dependency doesn't help since it's not there. Maybe if you're compiling with JDK 1.5 but targeting 1.3 or something like that?

2023-04-22 14:39 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
Even if, i don't know wether this really helps.

2023-04-22 22:04 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
I'm OK with removing this paragraph completely. The case that makes me pause is tools.jar. If I recall correctly that is not in the VM and also is not available from the Maven repo system. Is there any way to load that that is not a system dependency?

2023-04-22 22:06 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
I think if you custom-bundle Maven with your deps, e.g., extensions or so.

2023-04-23 10:45 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
I'm not quite sure what you mean. Do you mean some sort of fat jar? Or perhaps a custom version of Maven? Either way this seems much more complex than a system dependency that points to tools.jar. 

To move this PR forward, what specific change in the current text do you propose?

2023-04-23 14:43 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
My example was just have a custom JAR which you distribute across your company. That's it.

My proposal is to simply remove all examples regarding `system` and provide an abstract description/definition of this feature.

2025-01-22 12:48 UTC, slachiewicz commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
Agree, let's remove references to jdbc. Nowadays Oracle jdbc is normally available

2025-01-22 13:58 UTC, elharo commented on content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
> + examples are the JDBC standard extensions or the Java Authentication and Authorization
done

2025-01-22 15:43 UTC, slachiewicz approved these changes

2025-01-22 22:30 UTC, merged