[/MNGSITE-393} Remove legacy Maven 2 info
apache/maven-site pull request #212
Opened 2020-10-22 18:49 UTC by elharo

@michael-o

2020-10-22 19:29 UTC, michael-o requested changes
It's "Wagon" and "Wagon HTTP", they are names and not nouns.

2020-10-22 19:29 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  HTTP connection pooling prevents reopening http(s) to remote server for each requests.
This sentence is non-sense. It should read: HTTP connection pooling prevents opening new ones to remote server for each request.

2020-10-22 19:29 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  The default wagon http(s) is the HttpClient based on {{{http://hc.apache.org/httpcomponents-client-ga}Apache Http Client 4.1.2}}.
`{{{https://hc.apache.org/httpcomponents-client-4.5.x/}Apache Http Client 4.5.x}}

2020-10-27 16:34 UTC, michael-o requested changes

2020-10-27 16:34 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
` 1 800 000 ms`

2020-10-27 16:34 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
>    * http(s) connection pool: default to 20.
It is somewhat incomplete: https://github.com/apache/maven-wagon/blob/9b4f2fee4b0460aa16dee90d37a49440f09ed0db/wagon-providers/wagon-http-shared/src/main/java/org/apache/maven/wagon/shared/http/AbstractHttpClientWagon.java#L286-L295

2020-10-27 16:34 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  Without this setting, PUT requests that require authentication transfer their entire payload to the server before that server
This has been on by default for quite some time: https://github.com/apache/maven-wagon/blob/9b4f2fee4b0460aa16dee90d37a49440f09ed0db/wagon-providers/wagon-http-shared/src/main/java/org/apache/maven/wagon/shared/http/AbstractHttpClientWagon.java#L963-L967

2020-10-27 16:58 UTC, elharo commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
Why? That risks breaking the line in the middle of the number.

2020-10-27 16:58 UTC, elharo commented on content/apt/guides/mini/guide-http-settings.apt
> +  Without this setting, PUT requests that require authentication transfer their entire payload to the server before that server
What change do you suggest here?

2020-10-27 17:12 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
Simple: international audience, not English one. If you are worried about line breaks read [this](https://en.wikipedia.org/wiki/Thin_space) and use `&#8239;`

2020-10-27 17:14 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  Without this setting, PUT requests that require authentication transfer their entire payload to the server before that server
Leave it as-is, it does already the code `http.protocol.expect-continue=true`. I didn't read the entire seciton.

2020-10-27 17:36 UTC, elharo commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
I don't think there's any international standard on this unlike, for example, dates; and this page is written in English.

2020-10-27 18:23 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
Of course, there are: https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-concise-EN.pdf

2020-10-27 18:25 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
World's end is neither Rio Grande nor 49th parallel north.

2020-12-07 14:43 UTC, newblaque approved these changes

2023-04-23 10:58 UTC, elharo commented on content/apt/guides/mini/guide-http-settings.apt
> +  * readTimeout: default to 1,800,000ms (~30 minutes) (see section <<<Read time out>>> below)
reverted 1800000 since it's a Java property and this is the Java default value

2023-04-23 11:01 UTC, elharo commented on content/apt/guides/mini/guide-http-settings.apt
>    * http(s) connection pool: default to 20.
Please file a JIRA

2023-04-23 14:44 UTC, michael-o commented on content/apt/guides/mini/guide-http-settings.apt
>    * http(s) connection pool: default to 20.
This entire guide needs a review :-(

2023-04-23 14:45 UTC, michael-o approved these changes

2023-09-24 10:06 UTC, slachiewicz approved these changes
lgtm

2023-09-24 11:52 UTC, merged

2025-07-15 11:31 UTC, jira-importer commented
Resolve #969