document all allowed elements inside profiles
apache/maven-site pull request #214
Opened 2020-11-15 17:21 UTC by ninj

Previously the list was incomplete but did not infer the list was partial, e.g.
by using the word "some". If a user comes across the introductory guide first,
then it is easy to miss the complete model documentation and not find the
complete set of valid elements.

As discussed, the following have been updated:
- the remaining few elements have been added to complete the list.
- a link to the full model documentation is now provided.

2020-11-15 17:40 UTC, elharo commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  in the {{{/ref/current/maven-model/maven.html}maven model}}:
maven --> Maven
though I'm not sure this needs "as outlined
  in the {{{/ref/current/maven-model/maven.html}maven model}}". Might be better off just dropping it.

2020-11-15 17:51 UTC, ninj commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  in the {{{/ref/current/maven-model/maven.html}maven model}}:
Not having the reference to the model on this page meant I misunderstood what was allowed for a _very_ long time.
If you think it is cleaner, I could move the link into "the following POM elements" and remove the "as outlined..."

2020-11-15 17:53 UTC, michael-o commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  in the {{{/ref/current/maven-model/maven.html}maven model}}:
I agree with @elharo there is no need to duplicate information. Just reference with a link.

2020-11-15 18:00 UTC, ninj commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  in the {{{/ref/current/maven-model/maven.html}maven model}}:
done

2020-11-16 12:54 UTC, elharo requested changes

2020-11-16 12:54 UTC, elharo commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  {{{/ref/current/maven-model/maven.html}the following POM elements}}:
delete "the" as it's already on previous line

2020-11-16 18:16 UTC, ninj commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  {{{/ref/current/maven-model/maven.html}the following POM elements}}:
doh!

2020-11-16 18:17 UTC, ninj commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  {{{/ref/current/maven-model/maven.html}the following POM elements}}:
done

2020-11-16 18:20 UTC, elharo approved these changes

2020-11-16 18:20 UTC, merged