Maven Repositories documentation
apache/maven-site pull request #287
Opened 2022-01-19 14:12 UTC by cstamas

An attempt to create comprehensive documentation about Maven Repositories, something that is missing very much.

2022-01-19 14:45 UTC, michael-o commented on content/markdown/repositories/index.md
> +Apache Maven uses repositories to store build artifacts. Your dependencies are being downloaded from repositories,
remove build since POMs aren't build artifact, but are artifacts as well.

2022-01-19 14:45 UTC, michael-o commented on content/markdown/repositories/index.md
> +and your built artifacts are being stored (installed, uploaded) into repositories as well. This is one of the
same with typo

2022-01-19 14:45 UTC, michael-o commented on content/markdown/repositories/index.md
> +fundamental concept of Maven since its inception: Maven command line tool and Maven Repositories were mold together
concepts

2022-01-19 14:45 UTC, michael-o commented on content/markdown/repositories/index.md
> +and developed since inception of Maven project itself.
the inception

2022-01-19 14:46 UTC, michael-o commented on content/markdown/repositories/index.md
> +and developed since inception of Maven project itself.
the inception this is a repition of the former inception. Reads strange.

2022-01-19 14:47 UTC, michael-o commented on content/markdown/repositories/index.md
> +Maven addresses artifacts using coordinates, that are most often represented as `groupId`:`artifactId`:`version`,
I'd add the colon into the literal expression.

2022-01-19 14:47 UTC, michael-o commented on content/markdown/repositories/index.md
> +or GAV in short (or informally). The artifact coordinates uniquely describes the artifact you are referring to, but
describe

2022-01-19 14:47 UTC, michael-o commented on content/markdown/repositories/index.md
> +does not tell anything about its source (or origin). It is up to Maven to figure out (or you to tell Maven how
source => location. Source is rather an SCM, no?

2022-01-19 14:47 UTC, michael-o commented on content/markdown/repositories/layout.md
> +The layout is responsible to translate the artifact coordinates into generic path, that is later used to construct some
paths

2022-01-19 14:48 UTC, michael-o commented on content/markdown/repositories/layout.md
> +URI (file path, URL, it depends on context). Obviously, since Maven inception in 2002. the layout evolved as well.
Maven's inception

2022-01-19 14:48 UTC, michael-o commented on content/markdown/repositories/layout.md
> +URI (file path, URL, it depends on context). Obviously, since Maven inception in 2002. the layout evolved as well.
2002 w/o dot

2022-01-19 14:49 UTC, michael-o commented on content/markdown/repositories/layout.md
> +by some compute with file storage (where artifacts were laid down) and served by a HTTP server, essentially publishing
computer

2022-01-19 14:49 UTC, michael-o commented on content/markdown/repositories/layout.md
> +by some compute with file storage (where artifacts were laid down) and served by a HTTP server, essentially publishing
Repo isn't tied to HTTP

2022-01-19 14:50 UTC, michael-o commented on content/markdown/repositories/layout.md
> +way too much, it was not scaling in this setup.
Does it really make sense to describe the layout change? Who cares of our users?

2022-01-19 15:23 UTC, cstamas commented on content/markdown/repositories/index.md
> +Apache Maven uses repositories to store build artifacts. Your dependencies are being downloaded from repositories,
IMHO, a parent POM is a build artifact, but whatever :stuck_out_tongue:

2022-01-19 15:25 UTC, cstamas commented on content/markdown/repositories/index.md
> +does not tell anything about its source (or origin). It is up to Maven to figure out (or you to tell Maven how
source as "origin", not source as "source code"

2022-01-19 15:26 UTC, cstamas commented on content/markdown/repositories/layout.md
> +by some compute with file storage (where artifacts were laid down) and served by a HTTP server, essentially publishing
"from historical perspective, a remote repository was expected to be"...

2022-01-19 15:27 UTC, cstamas commented on content/markdown/repositories/layout.md
> +way too much, it was not scaling in this setup.
Our doco (and sources, plugins, etc) are still full of references to "legacy", so IMO is okay in short to cover this.

2022-01-20 07:26 UTC, hboutemy commented on content/markdown/repositories/index.md
> +of "project" and "parent project" (aka POMs):
very good question: here is my answer https://github.com/apache/maven-site/commit/22f23df1049da80b794eab430d415c56dfd97f54

2022-02-02 09:45 UTC, michael-o requested changes

2022-02-02 09:45 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +Artifact is "anything" that Maven downloads, installs or deploys for you. Most of them are POMs and JARs but
I think this is wrong because Maven also downloads metadata which isn't an artifact.

2022-02-02 09:47 UTC, cstamas commented on content/markdown/repositories/artifacts.md
> +Artifact is "anything" that Maven downloads, installs or deploys for you. Most of them are POMs and JARs but
I think we can dig into details incrementally. For start this is about "artifacts", while that is metadata.... a lot is missing about metadata, how plugin prefix is resolved, how snapshot version is resolved, etc.

2022-02-02 21:40 UTC, hboutemy commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
at minimum, requires collapse="true"

I'm not convinced that this topic deserves a 1st level menu entry: should be part of /repository directory and "Central Repository" menu, which is not only for Central but for all repositories, as described in https://maven.apache.org/repository/index.html image

2022-02-02 21:42 UTC, hboutemy commented on content/markdown/repositories/index.md
> +* [Remote Repositories](remote.md)
this intro has to be added to https://maven.apache.org/repository/index.html

2022-02-02 21:47 UTC, hboutemy commented on content/markdown/repositories/artifacts.md
> +| extension  | -> `jar`      |
not ok with the explanation on "project", "parent project", "build plugins" or "build extensions"

only the next explanation for dependencies is ok

2022-02-02 22:19 UTC, cstamas commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
Unsure why you want to blur central with maven remote repository... To me, it is like class vs class instance. Maven Central is "just one" instance of repositories.

2022-02-03 06:51 UTC, hboutemy commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
1. showing the class vs instance relationship is not blurring
2. did you look at the rendered menu? Do you think the new entries take the space that the topic deserves for normal users?

if you want to rename "Maven Central Repository" to "Maven Repository Center" (to match other menus) and that we add a sub-menu "Maven Central Repository", I love it

we need to look at rendered menu: currently https://i.imgur.com/aaoBS1R.png

2022-02-03 07:01 UTC, hboutemy commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
perhaps the image I did to summarize the relationship between Maven (on the user's desktop) and repositories and Central needs to be split in 2 topics ("Maven and repositories" where Central is just a simple block, and Central where we have the whole current Central yellow block) , because now we feel it is useful

2022-02-10 07:06 UTC, hboutemy commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
@cstamas @michael-o WDYT about these menus and pages demos?

2022-02-14 10:50 UTC, cstamas commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
Seems ok to me, let's move on

2022-02-14 22:17 UTC, hboutemy commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
"Maven Repository Centre" added as an additional commit to the branch

2022-09-09 11:53 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +but they have different values only in case of snapshots.
One additional property worth mentioning is a bit of special one: `baseVersion` that is actually derived from version (or the other way around, depending on the context): for release artifacts, it holds the same value as `version` whereas for snapshot artifacts, it holds the  "non-timestamped snapshot version". For example, for snapshot `version` "1.0-20220119.164608-1", the `baseVersion` would have the value "1.0-SNAPSHOT". So, `version` and `baseVersion` are linked, derived from each other,  but they have different values only in case of snapshots.

2022-09-09 11:59 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +Artifact is "anything" that Maven downloads, installs or deploys for you. Most of them are POMs and JARs but
> An artifact is ...

2022-09-09 12:05 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +the artifact can be really anything. A very important thing about artifacts is that they have coordinates,
the -> an
> an artifact can be

2022-09-09 12:05 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +Artifact is "anything" that Maven downloads, installs or deploys for you. Most of them are POMs and JARs but
> An artifact is "anything"

2022-09-09 12:05 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +Maven Core out of the box defines following "types" (ArtifactHandlers):
> Maven Core out of the box defines following "types" (handled by `ArtifactHandler` instances):

2022-09-09 12:05 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +So, from table above, we can see that if we define dependency type as "war", we will hit the "war" handler, that will
> we define the dependency type

2022-09-09 12:05 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +indirection does happen). More obvious is type "test-jar", where we end up with extension `jar`. Finally, the **any**
> The "test-jar" is more obvious and it translates to the `jar` extension.

2022-09-09 12:33 UTC, gnodet commented on content/markdown/repositories/artifacts.md
> +from `version` (or the other way around, depending on the context): for release artifacts, it holds the same value as
That still does not sounds good :-(

> that is actually derived from / linked to `version`, depending on the context.  For release artifacts...

2022-09-09 15:46 UTC, cstamas commented on content/markdown/repositories/layout.md
> +So the example artifact above not as GAV:
notEd

2022-09-09 15:48 UTC, cstamas commented on content/markdown/repositories/layout.md
> +And that is it! By applying this "algorithm" above to ANY Artifact we can, we can build up the path segment that
we can twice

2022-09-10 18:11 UTC, michael-o commented on content/site.xml
> +      <item name="Maven Repositories" href="/repositories/index.html">
I think that TL is Maven Repositories while Maven Central (Repository) is a sub menu of it with subpages since it is a special Maven repo instance.

2022-09-10 18:12 UTC, michael-o commented on content/site.xml
> +        </item>
Exactly the way I expect it to be.

2022-09-10 18:37 UTC, michael-o requested changes
Very nice writeup. Kudos!

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +An Artifact is "anything" (any file) that can be addressed using their coordinates, and Maven downloads, installs or
using its coor...

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +coordinates "GAV", not "GAVCE"). The artifact coordinate uniquely describe the artifact you are referring to,
The artifact coordinates

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +A word about uniqueness: as stated above, GAV coordinate uniquely identifies artifact, but only **within one repository**.
coordinates

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +contains artifact with same GAV). If those files are not-identical (truly, ie. hash-wise), it may cause severe
contain

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +contains artifact with same GAV). If those files are not-identical (truly, ie. hash-wise), it may cause severe
no hypen

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +While Maven internally uses notion of "artifact" thoroughly (just look at sources!), end user may never hit this name.
the notion

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +While Maven internally uses notion of "artifact" thoroughly (just look at sources!), end user may never hit this name.
end users

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +While Maven internally uses notion of "artifact" thoroughly (just look at sources!), end user may never hit this name.
name => term

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +"projects", "parent projects", "dependencies", "build plugins", "build extensions" and so on.
If so, maybe mention reporting plugins?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +## Artifact properties
Properties (upper case in titles/headings)

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +| artifactId   | The artifact name                                 |
Is that really a name? Not to be confused with `${project.name}`?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +| extension    | The artifact extension                            |
ext: default JAR maybe?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +One property worth explaining is a bit of special one: `baseVersion` that is actually derived/linked-to
no hyphen

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +| Artifact property | Project POM (pom.xml) | POM Artifact   |
Maven th consistently uppercase

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +| Artifact property | Plugin in Project POM                        | Plugin/Extension Artifact |
Maven th consistently uppercase

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +| Artifact property  | Dependency in Project POM                       | Dependency Artifact                       |
Maven th consistently uppercase

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +dependency resolution only):
during dep resolution?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +a "packaging" (lifecycle mapping) by providing ArtifactHandlers components with name corresponding to type name.
`ArtifactHandler`

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/artifacts.md
> +So, from table above, we can see that if we define the dependency type as "war", we will hit the "war" handler, that will
from the table

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/index.md
> +As you may know, Maven addresses artifacts using coordinates. The artifact coordinate uniquely describe the artifact
artifact coordinates

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/layout.md
> +The layout is responsible to translate the [artifact coordinates](artifacts.md) into generic paths, that is later used to construct some
for translating

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/layout.md
> +# A word about Maven1 layout
Does it really make sense to describe this?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/local.md
> +The local repository is mixed bag, in sense, that it serves two purposes: it caches downloaded artifacts from
is a mixed...

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/local.md
> +As noted on [Layout](layout.md) page, locally built and installed (implies "to local repository") artifacts will use
noted in

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/metadata.md
> +for Maven. These metadata files are **not Artifacts**, and hence, are not addressable by Maven users. They are instead
Why highlight both words and not just "not"?

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +Remote repositories usually refers to repositories like [Maven Central Repository](/repository/index.html) is. These
refer

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +Remote repositories usually refers to repositories like [Maven Central Repository](/repository/index.html) is. These
~~is~~

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +Your POM locally usually contains snapshot version in a form of string that ends with "SNAPSHOT" constant string
contains snapshot versions...

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +Your POM locally usually contains snapshot version in a form of string that ends with "SNAPSHOT" constant string
in a form of a string

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +"SNAPSHOT" anymore, but a time stamp and build number. Also, during deploy, Maven will deploy required Maven V Level Metadata
timestamp

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +Where the date (used in `YYYYMMDD.HHMMSS` format) is constant across deploy from same session (is time when Maven
Please add that this timestamp is *always*  in * Etc/UTC`.

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +### Consuming Snapshot Artifact
Artifacts

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +If your project depends on SNAPSHOT dependency, the POM of your project usually contains `version` value that ends
depencencies

2022-09-10 18:37 UTC, michael-o commented on content/markdown/repositories/remote.md
> +with "SNAPSHOT" (for example "1.0-SNAPSHOT"), still, as we see above, remote repository does NOT contain such versions,
remote repositories do..

2022-09-26 08:58 UTC, michael-o approved these changes

2022-09-27 06:11 UTC, merged

2025-07-15 11:33 UTC, jira-importer commented
Resolve #1040