[MNG-7463] Improve documentation about deprecation in Mojo
apache/maven-site pull request #319
Opened 2022-08-22 21:42 UTC by slawekjaranowski

2022-08-25 13:26 UTC, michael-o requested changes

2022-08-25 13:26 UTC, michael-o commented on content/xdoc/developers/mojo-api-specification.xml
> +          <td>Description with the reason of Mojo depreciation. Similar to Javadoc deprecated.
deprecation

2022-08-25 13:26 UTC, michael-o commented on content/xdoc/developers/mojo-api-specification.xml
> +            This will trigger a warning when a user tries to use Mojo marked as deprecated.
use a Mojo

2022-08-25 13:26 UTC, michael-o commented on content/xdoc/developers/mojo-api-specification.xml
> +          <td>Description with the reason of parameter depreciation. Similar to Javadoc deprecated.
same here

2022-08-28 13:28 UTC, slawekjaranowski commented
@michael-o Fixed according to comments.

2022-08-28 17:09 UTC, michael-o requested changes

2022-08-28 17:09 UTC, michael-o commented on content/xdoc/developers/mojo-api-specification.xml
> +          <td>Description with the reason of Mojo depreciation. Similar to Javadoc deprecation.
Still typo

2022-08-28 17:09 UTC, michael-o commented on content/xdoc/developers/mojo-api-specification.xml
> +          <td>Description with the reason of parameter depreciation. Similar to Javadoc deprecation.
Same here

2022-08-28 17:11 UTC, michael-o commented
See: https://www.oxfordlearnersdictionaries.com/definition/english/deprecation?q=deprecation

2022-08-30 06:52 UTC, slawekjaranowski commented
I see ... such a similar words  ... 😄

2022-08-30 07:07 UTC, michael-o approved these changes

2022-08-30 07:22 UTC, merged