Clarify language around exclusions
apache/maven-site pull request #337
Opened 2022-11-13 14:44 UTC by elharo

@michael-o

2022-11-13 17:00 UTC, michael-o requested changes

2022-11-13 17:00 UTC, michael-o commented on content/apt/pom.apt.vm
> +  It is sometimes useful to limit  a dependency's transitive dependencies. A dependency may have incorrectly
double space

2022-11-13 17:00 UTC, michael-o commented on content/apt/pom.apt.vm
> +      <version>3.8.6</version>
I think we even have a property for this in the POM.

2023-02-06 12:23 UTC, elharo commented on content/apt/pom.apt.vm
> +      <version>3.8.6</version>
which property is that?

2023-02-06 12:24 UTC, elharo commented on content/apt/pom.apt.vm
> +  It is sometimes useful to limit  a dependency's transitive dependencies. A dependency may have incorrectly
fixed

2023-02-06 13:04 UTC, michael-o commented on content/apt/pom.apt.vm
> +      <version>3.8.6</version>
currentStableVersion

2023-02-06 15:51 UTC, elharo commented on content/apt/pom.apt.vm
> +      <version>3.8.6</version>
done

2023-02-06 16:54 UTC, michael-o approved these changes

2023-03-24 11:54 UTC, merged