[MNGSITE-501] Clarify profile jdk activation
apache/maven-site pull request #346
Opened 2022-11-30 19:37 UTC by kwin

2022-11-30 20:49 UTC, gnodet requested changes

2022-11-30 20:49 UTC, gnodet commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  version <starts with> "1.4" (eg. "1.4.0_08", "1.4.2_07", "1.4"), particularly it <won't be active>
`particularly` -> `in particular`

2022-11-30 20:49 UTC, gnodet commented on content/apt/guides/introduction/introduction-to-profiles.apt
> -  the value of a system property. Here are some examples.
`prefix` seems an important word to describe what happens here.  Is that a willingful removal ?

2022-11-30 20:49 UTC, gnodet commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  the presence of a system property or the value of a system property. Here are some examples.
`the presence or value of a system property.`

2022-11-30 20:50 UTC, kwin commented on content/apt/guides/introduction/introduction-to-profiles.apt
> -  the value of a system property. Here are some examples.
well prefix matching is just one possibility as version ranges are supported as well

2022-12-01 07:19 UTC, kwin commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  matching of the JDK version, matching the operating system,
Fixed in https://github.com/apache/maven-site/pull/346/commits/d93b461cf74b40dc8fb8ca96d8c6f6538be810be.

2022-12-01 07:19 UTC, kwin commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  the presence of a system property or the value of a system property. Here are some examples.
Fixed in https://github.com/apache/maven-site/pull/346/commits/d93b461cf74b40dc8fb8ca96d8c6f6538be810be.

2022-12-01 07:20 UTC, kwin commented on content/apt/guides/introduction/introduction-to-profiles.apt
> +  version <starts with> "1.4" (eg. "1.4.0_08", "1.4.2_07", "1.4"), particularly it <won't be active>
Fixed in https://github.com/apache/maven-site/pull/346/commits/d93b461cf74b40dc8fb8ca96d8c6f6538be810be.

2022-12-05 09:53 UTC, merged

2025-07-15 11:36 UTC, jira-importer commented
Resolve #1107