#MNGSITE-539 Add Maven CI Friendly Versions to menu
apache/maven-site pull request #594
Opened 2024-12-15 19:58 UTC by Bukama

The guide about Maven CI Friend Versions was integrated into the navigation menu. As it is a guide, the file was moved to the guide section and renamed to match the naming schema of this folder. Therefor the release notes of Maven 3.5.0 (and its beta) was updated to the new links. Also some small formatting errors in those release notes were fixed in the same action.

2024-12-15 20:00 UTC, Bukama commented
Note: Spotless was applied and IDE is set to the [Maven code styles](https://maven.apache.org/developers/conventions/code.html#Generic_Code_Style_And_Convention) (for MD files esp. 120 chars per line). The files were not matching the code styles before (lines of 177 chars and more)

2024-12-16 15:22 UTC, Bukama commented
> Can you split the PR so that we can review the reformat / actual changes ?

Yeah sure. Opened #595 to just contain the formatting of the effected files. Will then rebase/redo the actual changes to add the guide to the menu etc.

2024-12-22 22:59 UTC, slawekjaranowski commented
#595 merged

2024-12-23 08:56 UTC, Bukama commented
> #595 merged

Thank you, rebased this branch.

2024-12-23 12:15 UTC, elharo requested changes

2024-12-23 12:15 UTC, elharo commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +  or `mvn deploy` more details can be found at [Maven CI Friendly Versions](/guides/mini/guide-maven-ci-friendly.html).
run-on sentence

2024-12-23 12:15 UTC, elharo commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +* [MNG-6177] - The `--file` command line option of the Windows and Unix launchers does not work for directory names like
but 9it does work on Macs?

2024-12-23 12:26 UTC, Bukama commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +  or `mvn deploy` more details can be found at [Maven CI Friendly Versions](/guides/mini/guide-maven-ci-friendly.html).
> run-on sentence

Can you explain what you mean? Do you want me to change the "to do an `mvn install`" to "to run `mvn install`"? 
My PR does not aim to change the wording of the release notes, but I'm open to do it.

2024-12-23 12:33 UTC, Bukama commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +* [MNG-6177] - The `--file` command line option of the Windows and Unix launchers does not work for directory names like
I don't know, maybe @cstamas @gnodet @slawekjaranowski do? To be fair the ticket was closed in 2017

2024-12-23 12:38 UTC, elharo commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +* [MNG-6177] - The `--file` command line option of the Windows and Unix launchers does not work for directory names like
I'm not clear on why you're changing this at all. If you are then,

If you are using the previously named properties for a version in your pom, you have to use [flatten-maven-plugin to do an `mvn install`
  or `mvn deploy`. More details can be found at [Maven CI Friendly Versions](/guides/mini/guide-maven-ci-friendly.html).

2024-12-23 13:14 UTC, Bukama commented on content/markdown/docs/3.5.0-beta-1/release-notes.md
> +  or `mvn deploy` more details can be found at [Maven CI Friendly Versions](/guides/mini/guide-maven-ci-friendly.html).
> I'm not clear on why you're changing this at all. If you are then,
> 
> If you are using the previously named properties for a version in your pom, you have to use [flatten-maven-plugin to do an `mvn install` or `mvn deploy`. More details can be found at [Maven CI Friendly Versions](/guides/mini/guide-maven-ci-friendly.html).

I'm only changing this to update the link in the release notes. It was not my intend to change the wording, but updated it to your suggestion.

2024-12-23 13:49 UTC, elharo approved these changes

2024-12-23 14:27 UTC, slawekjaranowski commented on content/markdown/guides/mini/guide-maven-ci-friendly.md
please also add redirect to .htaccess

2024-12-23 14:51 UTC, Bukama commented on content/markdown/guides/mini/guide-maven-ci-friendly.md
Added

2024-12-23 14:56 UTC, slawekjaranowski approved these changes

2024-12-23 15:04 UTC, merged

2025-07-15 11:36 UTC, jira-importer commented
Resolve #1125