Enable GitHub issues
apache/maven-site pull request #599
Opened 2024-12-21 14:24 UTC by slawekjaranowski

I hope that we not need an issues migration for this project - it is simply current state of site.

We have 69 issues opened now:
https://issues.apache.org/jira/projects/MNGSITE

After it we can create a pined issue with information and link to JIRA

Next steps after merge:
 - make JIRA project read-only
 - add issues template - will be a good test for other projects, its also can have a link to JIRA

2024-12-21 15:05 UTC, Bukama approved these changes
According the removal of the JIRA link: When not migrating issues, shall we keep the link for some time with the note that it's read only (assuming that JIRA issue creation will be disabled as discussed on mailing list)?

Aside from this: non binding approval

2024-12-21 15:57 UTC, slawekjaranowski commented
> According the removal of the JIRA link: When not migrating issues, shall we keep the link for some time with the note that it's read only (assuming that JIRA issue creation will be disabled as discussed on mailing list)?
> 

I will add an pined issue with information and template which also contain JIRA link

2024-12-21 16:10 UTC, slawekjaranowski commented
Issues template added.

2024-12-21 16:48 UTC, Bukama commented on .github/ISSUE_TEMPLATE/FORM-BUG.yml
> +      description: Please describe a bug
`a bug` to `the bug` maybe?
I would also point out to specify the expected behavior, not only a description of the "seen" behavior.

2024-12-21 20:17 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/FORM-BUG.yml
> +      description: Please describe a bug
ok there is next proposition

2024-12-21 20:20 UTC, slawekjaranowski commented
Issue page will be look like:

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/b85e5354-02ad-47c2-884e-00df416255ba" />

bug report:
<img width="906" alt="image" src="https://github.com/user-attachments/assets/72b55f0b-dea5-4310-9e73-b6b34dafc044" />

and 
<img width="906" alt="image" src="https://github.com/user-attachments/assets/b63659b2-b624-4bb1-859e-61a617156bee" />

2024-12-22 16:09 UTC, Bukama commented
Thanks for the preview to get a better idea how it will look. My thoughts below.

> Issue page will be look like:
> 

General:
I link that you thank people to take the time to fill out the forms - we value their time and effort!

The part "and answer" part of "Please ask and answer on the mailing list" sounds strange, like "Please ask your question on the mailing list - oh and answer it by yourself too please, so we don't have to - thanks!" 🙈


Issue page:
I think you want to create a template, easily reuseable by other repositories, but as were are in the context of a website, maybe we should rephrase "File a bug report" to something containing also "mistake" or "error" aiming at outdated or wrong information on the website (in contrast to a technical bug, like broken links etc.). But maybe that's just me focusing on texts for non/less IT people (what I write a lot at work).


Bug report:
"An/Opening issue is not needed..."

In site's context I think this is okay, but I don't like it in general as it may result in situations where people try fixing something which is either not wrong or do it in a wrong way. What I want to say with this: I like to discuss / agree on bugs before fixing them (more true in open source projects than at my work where all have good knowledge of the code and system).

The title and description should be a required field. 


Improvement:
The title and description should be a required field.

2024-12-23 11:32 UTC, elharo requested changes

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
Is "with fixing" correct? It sounds off.

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/BUG.yml
> +    id: massage
Is massage correct? That's a strange ID for this project. Was perhaps message meant?

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/BUG.yml
> +      label: Maven site address where bug exist
exists
Possibly change address to location or URL

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/IMPROVEMENT.yml
> +name: Improvement proposition
Proposal

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/IMPROVEMENT.yml
> +description: File a improvement proposition.
an improvement proposal
or maybe
a proposal for improvement

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/IMPROVEMENT.yml
> +        Thanks for taking the time to fill out this improvement proposition!
No exclamation points please.

2024-12-23 11:32 UTC, elharo commented on .github/ISSUE_TEMPLATE/IMPROVEMENT.yml
> +      label: Improvement proposition.
proposal

2024-12-23 11:34 UTC, elharo reviewed
I'm unclear on what happens to old issues under this proposal. Are they now available in github or not? Or are some available and some not? And of so which ones?

2024-12-23 12:05 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
My idea is to not required issue creating if someone has a plan to make a PR in the same time. 

Big or more complicated planned change should have an issue to first discuss before starting implementation.

So how to say in simple way?

2024-12-23 12:06 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/BUG.yml
> +    id: massage
`id` is a technical required field - must be unique

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#keys

2024-12-23 12:17 UTC, slawekjaranowski commented
> I'm unclear on what happens to old issues under this proposal. Are they now available in github or not? Or are some available and some not? And of so which ones?

My proposition is to not migrate as we have a link to old jira in templates and we can continue work on in. 

We should only block creating new issues in JIRA.

2024-12-23 12:20 UTC, elharo commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
"Simple fixes in single PRs do not require issues."

That said, some (not all) simple fixes do require issues. For instance, a one-line change that fixes a really serious bug should have an issue to show up in the release notes, but a one line change that corrects a spelling error in a comment should not.

2024-12-23 12:46 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/FORM-BUG.yml
> +      description: Please describe a bug
as it is documentation project I would not to complicate the bug form

2024-12-23 13:00 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
It is a documentation site ... so we don't have a release notes here  - it is current state only.

2024-12-23 13:50 UTC, Bukama commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
In general I'm with @elharo (and I normally create issues for everything), but I see @slawekjaranowski point as it's a documentation site. So I suggest to take Elliotte's suggestion:

> "Simple fixes in single PRs do not require issues."

2024-12-23 14:01 UTC, slawekjaranowski commented on .github/ISSUE_TEMPLATE/BUG.yml
> +        Issue is **not needed** if you want to create a Pull Request with fixing.
done in the latest version

2024-12-23 14:04 UTC, Bukama commented
> > I'm unclear on what happens to old issues under this proposal. Are they now available in github or not? Or are some available and some not? And of so which ones?
> 
> My proposition is to not migrate as we have a link to old jira in templates and we can continue work on in.

Benefit of a migration is the better visibility, but that's more a temporal problem (if one at all). In terms of the documentation site I'm totally open for migrate them or not. Mostly depends on how many issue are open.

(Keep in mind, my opinion is non-binding).

2024-12-23 14:05 UTC, Bukama approved these changes

2024-12-23 23:28 UTC, slachiewicz approved these changes

2024-12-24 15:12 UTC, elharo approved these changes

2025-01-03 14:00 UTC, merged