[MNGSITE-504] Fix rendering / markdown warnings
apache/maven-site pull request #614
Opened 2024-12-29 16:38 UTC by Bukama

With this PR I updated some very old (, but still existing) pages to reduce the renderer warnings during the `site` goal (see MNGSITE-504).

This PR is **not* to update the outdated content of those pages!

I could fix all warnings in the existing files, except the following four:

```
[WARNING] Unrecognized xdoc tag <base> at [32:52]
[WARNING] Unrecognized xdoc tag <link> at [34:100]
[WARNING] Unrecognized xdoc tag <link> at [35:75]
[WARNING] Unrecognized xdoc tag <link> at [36:90]
```

These are from CSS definition in the `errors/404.xml.vm`. I couldn't find a documentation how to define them properly, esp. as we need dynamic links. This why I transformed the page to a markdown file.

2024-12-29 18:37 UTC, elharo commented on content/markdown/errors/404.md
> +<!--
I don't think markdown supports comments?

2024-12-29 18:56 UTC, slawekjaranowski requested changes

2024-12-29 18:56 UTC, slawekjaranowski commented on content/xdoc/errors/404.xml.vm
We can not move it to `md`
We need additional html page headers.

This content can be displayed in any path .... and without those header content will be corrupted.

@kwin @michael-o can we add html headers in `md` format?

2024-12-29 19:32 UTC, Bukama commented on content/xdoc/errors/404.xml.vm
> We can not move it to `md` We need additional html page headers.
> 
> This content can be displayed in any path .... and without those header content will be corrupted.
> 
> @kwin @michael-o can we add html headers in `md` format?

To add as an information what I've tested locally:
I checked the `.htaccess` which redirects to this in case of 404 and I checked if `/errors/404.html` is displayed correctly - which it is.
But I'm honest: I'm not very experienced with `.htaccess` file (as you probably already noticed).

2024-12-29 19:38 UTC, Bukama commented on content/markdown/errors/404.md
> +<!--
> I don't think markdown supports comments?

Works fine:
![image](https://github.com/user-attachments/assets/1004ce2e-bc81-4cbd-9c37-a49bb1209f90)

2024-12-29 21:04 UTC, elharo commented on content/markdown/errors/404.md
> +<!--
I think that's a function of some particular implementation that extends the spec. I'm not sure we can/should rely on that.

2024-12-29 21:19 UTC, Bukama commented on content/markdown/errors/404.md
> +<!--
> I think that's a function of some particular implementation that extends the spec. I'm not sure we can/should rely on that.

Then we need to change **all** other `.md` files too and remove every comments and licences there...

2024-12-29 21:21 UTC, slawekjaranowski commented on content/xdoc/errors/404.xml.vm
The problem will be on page like: https://maven.apache.org/plugins/maven-abc-plugin/

2024-12-29 21:35 UTC, michael-o commented on content/markdown/errors/404.md
> +<!--
No, that is a bug @kwin had ready fixed.on master.

2024-12-29 21:42 UTC, elharo commented on content/markdown/errors/404.md
> +<!--
My bad. I forgot about inline HTML. This is OK synatctically

2024-12-30 08:30 UTC, Bukama commented on content/xdoc/errors/404.xml.vm
Okay, will wait for an answer of @kwin or @michael-o about your question and then change or revert the 404 file

2025-01-01 12:09 UTC, kwin commented on content/xdoc/errors/404.xml.vm
In general every valid HTML is also valid in MD (https://daringfireball.net/projects/markdown/syntax#html). This is more a question on how the resulting HTML is being partitioned by the doxia-sitetools (to inject things like navigation).

2025-01-01 12:24 UTC, Bukama commented on content/xdoc/errors/404.xml.vm
> In general every valid HTML is also valid in MD (https://daringfireball.net/projects/markdown/syntax#html). This is more a question on how the resulting HTML is being partitioned by the doxia-sitetools (to inject things like navigation).

Thank you for your response. For the moment I reverted the changes in the 404 (meaning the `vm` is back there and the `md` is gone), until we are sure. To change the 404 to MD is done in few mins anyway.
But this means that the rendering warnings, caused by this page (double title and the HTTP `Unrecognized xdoc tag` are back in place)

2025-01-01 16:16 UTC, Bukama commented on content/xdoc/errors/404.xml.vm
Side note: Did some tests about using test and filed an issue [DOXIASITETOOLS-358](https://issues.apache.org/jira/browse/DOXIASITETOOLS-358)

2025-01-04 16:54 UTC, Bukama commented
Rebased after several other commits were merged into master

2025-01-04 17:11 UTC, merged

2025-07-15 11:36 UTC, jira-importer commented
Resolve #1110