Change PNG to plantUML image in subprojects guide
apache/maven-site pull request #618
Opened 2024-12-31 18:01 UTC by Bukama

Image about how it looked before and with this update

![Comparison](https://github.com/Bukama/MavenStuff/raw/main/Maven4/puml/puml_multisubproject.png)

2024-12-31 18:02 UTC, Bukama commented
@slawekjaranowski @mthmulders Please review :)

2024-12-31 20:05 UTC, mthmulders requested changes

2024-12-31 20:05 UTC, mthmulders commented on content/markdown/guides/mini/guide-multiple-subprojects-4.md
The example Maven invocations in line 171 - 176 of this Markdown file need to be changed, as the diagram uses different module names / project names now. Or the PlantUML source should keep the same naming convention as the text (`module-a` instead of `subprojectA`).

This is not only about "module" vs "project" but also about the kebab-case vs. camel-case.

2024-12-31 20:19 UTC, Bukama commented on content/markdown/guides/mini/guide-multiple-subprojects-4.md
Oops 👀 
Updates the puml diagramm. Looks like this now:

![image](https://github.com/user-attachments/assets/8bb89426-4bd6-4d3b-b20f-ef48c581fe91)

2024-12-31 22:05 UTC, mthmulders commented on content/markdown/guides/mini/guide-multiple-subprojects-4.md
Excellent, thank you!

2024-12-31 22:07 UTC, mthmulders approved these changes

2025-01-03 16:51 UTC, slawekjaranowski commented on content/resources/guides/mini/keepDir
Is it needed?

2025-01-03 19:30 UTC, Bukama commented on content/resources/guides/mini/keepDir
at least locally the site runs without it. I removed it.

2025-01-03 20:41 UTC, slawekjaranowski approved these changes

2025-01-03 20:42 UTC, merged